INFO     root:test_calculator.py:37 Starting test for valid addition operation with login.
INFO     root:test_calculator.py:44 Attempting to log in with credentials: {'userName': 'admin', 'password': '123'}