{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "failed", "statusDetails": {"message": "AssertionError: assert 8 == None", "trace": "self = <test_calc.TestCalculate object at 0x00000233118E3410>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('1')\n        self.login_page.log_in('admin','123')\n        logging.info('2')\n    \n        self.calculator_page.calc_add('5','3')\n        logging.info('3')\n    \n        result = self.calculator_page.calc_result()\n>       assert 8 == result\nE       assert 8 == None\n\ntest_calc.py:49: AssertionError"}, "attachments": [{"name": "log", "source": "5d86c404-e713-47a3-9c98-6b136388f578-attachment.txt", "type": "text/plain"}], "start": 1745343888794, "stop": 1745343889326, "uuid": "4eb429c2-f09e-4996-ad5d-7076b55a5d95", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}