{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "failed", "statusDetails": {"message": "AssertionError: assert '8' == ''\n  + 8", "trace": "self = <test_calc.TestCalculate object at 0x0000014C64A4B410>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('1')\n        self.login_page.log_in('admin','123')\n        logging.info('2')\n    \n        self.calculator_page.calc_add('5','3')\n        logging.info('3')\n    \n        result = self.calculator_page.get_result()\n        logging.info('4')\n>       assert '8' == result\nE       AssertionError: assert '8' == ''\nE         + 8\n\ntest_calc.py:50: AssertionError"}, "attachments": [{"name": "log", "source": "131fea14-a34a-4ea7-ae1d-4bfce6d0c78c-attachment.txt", "type": "text/plain"}], "start": 1745344562216, "stop": 1745344562729, "uuid": "1ad1e56b-7165-4ba5-9556-a11c767af608", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "24148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}