DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:101 Selenium Manager binary found at: C:\Users\User\anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:114 Executing process: C:\Users\User\anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --debug --language-binding python --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chromedriver not found in PATH
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chrome detected at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Running command: wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Output: "\r\r\n\r\r\nVersion=135.0.7049.96\r\r\n\r\r\n\r\r\n\r"
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Detected browser: chrome 135.0.7049.96
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Required driver: chromedriver 135.0.7049.95
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chromedriver 135.0.7049.95 already in the cache
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Driver path: C:\Users\User\.cache\selenium\chromedriver\win64\135.0.7049.95\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Browser path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.service:service.py:231 Started executable: `C:\Users\User\.cache\selenium\chromedriver\win64\135.0.7049.95\chromedriver.exe` in a child process with pid: 19392 using 0 to output -3
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:403 POST http://localhost:52920/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'goog:chromeOptions': {'extensions': [], 'binary': 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', 'args': ['headless']}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:243 Starting new HTTP connection (1): localhost:52920
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52920 "POST /session HTTP/11" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:436 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"135.0.7049.96","chrome":{"chromedriverVersion":"135.0.7049.95 (de2eb485a1951079e63bdb57ce25544d2dc79c15-refs/branch-heads/7049@{#1836})","userDataDir":"C:\\Users\\User\\AppData\\Local\\Temp\\scoped_dir19392_1182380177"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:52925"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"82ae0eb06521f3a77c3bf7cf8b011ec9"}} | headers=HTTPHeaderDict({'Content-Length': '881', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:465 Finished Request
INFO     root:test_calculator.py:93 Starting test for valid subtraction operation with login.
INFO     root:test_calculator.py:100 Attempting to log in with credentials: {'userName': 'admin', 'password': '123'}
INFO     root:test_calculator.py:102 Login response status code: 200
INFO     root:test_calculator.py:105 Login response data: {'message': None, 'data': {'success': True, 'token': '6214a128-ac9b-4e75-b498-ec0c39990c3d'}, 'status': 'success'}
INFO     root:test_calculator.py:107 Login response data: {'message': None, 'data': {'success': True, 'token': '6214a128-ac9b-4e75-b498-ec0c39990c3d'}, 'status': 'success'}
INFO     root:test_calculator.py:109 Received token: 6214a128-ac9b-4e75-b498-ec0c39990c3d
INFO     root:test_calculator.py:117 Sending calculation request: {'op1': 10, 'operation': '-', 'op2': 3}
INFO     root:test_calculator.py:122 Received response with status code: 200
INFO     root:test_calculator.py:125 Calculation response data: {'message': None, 'data': 7, 'status': 'success'}
INFO     root:test_calculator.py:131 The result of the addition operation is correct.
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:403 DELETE http://localhost:52920/session/82ae0eb06521f3a77c3bf7cf8b011ec9 {}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52920 "DELETE /session/82ae0eb06521f3a77c3bf7cf8b011ec9 HTTP/11" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:436 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:465 Finished Request