DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:101 Selenium Manager binary found at: C:\Users\User\anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:114 Executing process: C:\Users\User\anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --debug --language-binding python --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chromedriver not found in PATH
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chrome detected at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Running command: wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Output: "\r\r\n\r\r\nVersion=135.0.7049.96\r\r\n\r\r\n\r\r\n\r"
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Detected browser: chrome 135.0.7049.96
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Required driver: chromedriver 135.0.7049.95
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chromedriver 135.0.7049.95 already in the cache
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Driver path: C:\Users\User\.cache\selenium\chromedriver\win64\135.0.7049.95\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Browser path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.service:service.py:231 Started executable: `C:\Users\User\.cache\selenium\chromedriver\win64\135.0.7049.95\chromedriver.exe` in a child process with pid: 1628 using 0 to output -3
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:403 POST http://localhost:52435/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'goog:chromeOptions': {'extensions': [], 'binary': 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', 'args': ['headless']}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:243 Starting new HTTP connection (1): localhost:52435
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52435 "POST /session HTTP/11" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:436 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"135.0.7049.96","chrome":{"chromedriverVersion":"135.0.7049.95 (de2eb485a1951079e63bdb57ce25544d2dc79c15-refs/branch-heads/7049@{#1836})","userDataDir":"C:\\Users\\User\\AppData\\Local\\Temp\\scoped_dir1628_24863143"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:52438"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"6501ab1c7381a5296a68fd4407f8dd4b"}} | headers=HTTPHeaderDict({'Content-Length': '878', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:465 Finished Request
INFO     root:test_calculator.py:232 Starting test for valid subtraction operation with login.
INFO     root:test_calculator.py:239 Attempting to log in with credentials: {'userName': 'admin', 'password': '123'}
INFO     root:test_calculator.py:241 Login response status code: 200
INFO     root:test_calculator.py:244 Login response data: {'message': None, 'data': {'success': True, 'token': '76f46cf8-a6f5-4a4d-90f0-d895188bc345'}, 'status': 'success'}
INFO     root:test_calculator.py:246 Login response data: {'message': None, 'data': {'success': True, 'token': '76f46cf8-a6f5-4a4d-90f0-d895188bc345'}, 'status': 'success'}
INFO     root:test_calculator.py:248 Received token: 76f46cf8-a6f5-4a4d-90f0-d895188bc345
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:403 DELETE http://localhost:52435/session/6501ab1c7381a5296a68fd4407f8dd4b {}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52435 "DELETE /session/6501ab1c7381a5296a68fd4407f8dd4b HTTP/11" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:436 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:465 Finished Request