DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:101 Selenium Manager binary found at: C:\Users\User\anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:114 Executing process: C:\Users\User\anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --debug --language-binding python --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Sending stats to Plausible: Props { browser: "chrome", browser_version: "", os: "windows", arch: "amd64", lang: "python", selenium_version: "4.31" }
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chromedriver not found in PATH
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chrome detected at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Running command: wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Output: "\r\r\n\r\r\nVersion=135.0.7049.96\r\r\n\r\r\n\r\r\n\r"
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Detected browser: chrome 135.0.7049.96
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Required driver: chromedriver 135.0.7049.95
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 chromedriver 135.0.7049.95 already in the cache
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Driver path: C:\Users\User\.cache\selenium\chromedriver\win64\135.0.7049.95\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:140 Browser path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.service:service.py:231 Started executable: `C:\Users\User\.cache\selenium\chromedriver\win64\135.0.7049.95\chromedriver.exe` in a child process with pid: 26540 using 0 to output -3
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:403 POST http://localhost:62775/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'goog:chromeOptions': {'extensions': [], 'binary': 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', 'args': ['headless']}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:243 Starting new HTTP connection (1): localhost:62775
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:62775 "POST /session HTTP/11" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:436 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"135.0.7049.96","chrome":{"chromedriverVersion":"135.0.7049.95 (de2eb485a1951079e63bdb57ce25544d2dc79c15-refs/branch-heads/7049@{#1836})","userDataDir":"C:\\Users\\User\\AppData\\Local\\Temp\\scoped_dir26540_626541015"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:62780"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"999616f070cbd66dec48dc43697023f6"}} | headers=HTTPHeaderDict({'Content-Length': '880', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:465 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:403 POST http://localhost:62775/session/999616f070cbd66dec48dc43697023f6/url {'url': 'http://127.0.0.1:7000/'}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:62775 "POST /session/999616f070cbd66dec48dc43697023f6/url HTTP/11" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:436 Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=135.0.7049.96)","stacktrace":"\tGetHandleVerifier [0x00007FF6BEE75355+78597]\n\tGetHandleVerifier [0x00007FF6BEE753B0+78688]\n\t(No symbol) [0x00007FF6BEC291AA]\n\t(No symbol) [0x00007FF6BEC25BA0]\n\t(No symbol) [0x00007FF6BEC16849]\n\t(No symbol) [0x00007FF6BEC185A8]\n\t(No symbol) [0x00007FF6BEC16B56]\n\t(No symbol) [0x00007FF6BEC165D6]\n\t(No symbol) [0x00007FF6BEC1629A]\n\t(No symbol) [0x00007FF6BEC13F4A]\n\t(No symbol) [0x00007FF6BEC1471C]\n\t(No symbol) [0x00007FF6BEC2D07A]\n\t(No symbol) [0x00007FF6BECD002E]\n\t(No symbol) [0x00007FF6BECA70EA]\n\t(No symbol) [0x00007FF6BECCF2BB]\n\t(No symbol) [0x00007FF6BECA6EC3]\n\t(No symbol) [0x00007FF6BEC703F8]\n\t(No symbol) [0x00007FF6BEC71163]\n\tGetHandleVerifier [0x00007FF6BF11EF0D+2870973]\n\tGetHandleVerifier [0x00007FF6BF1196B8+2848360]\n\tGetHandleVerifier [0x00007FF6BF136993+2967875]\n\tGetHandleVerifier [0x00007FF6BEE9019A+188746]\n\tGetHandleVerifier [0x00007FF6BEE9847F+222255]\n\tGetHandleVerifier [0x00007FF6BEE7D2D4+111236]\n\tGetHandleVerifier [0x00007FF6BEE7D482+111666]\n\tGetHandleVerifier [0x00007FF6BEE635A9+5465]\n\tBaseThreadInitThunk [0x00007FFC0CC37374+20]\n\tRtlUserThreadStart [0x00007FFC0D8BCC91+33]\n"}} | headers=HTTPHeaderDict({'Content-Length': '1304', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:465 Finished Request